"""Module for look-up-table like objects"""
import os

host = os.environ.get("API_HOSTNAME") or "https://earthmaps.io"

bbox_offset = 0.000000001

landcover_names = {
    0: {"type": "No Data at this location.", "color": "#ffffff"},
    1: {"type": "Temperate or sub-polar needleleaf forest", "color": "#003d00"},
    2: {"type": "Sub-polar taiga or needleleaf forest", "color": "#949c70"},
    5: {
        "type": "Temperate or sub-polar broadleaf deciduous forest",
        "color": "#148c3d",
    },
    6: {"type": "Mixed forest", "color": "#5c752b"},
    8: {"type": "Temperate or sub-polar shrubland", "color": "#b38a33"},
    10: {"type": "Temperate or sub-polar grassland", "color": "#e1cf8a"},
    11: {"type": "Sub-polar or polar shrubland-lichen-moss", "color": "#9c7554"},
    12: {"type": "Sub-polar or polar grassland-lichen-moss", "color": "#bad48f"},
    13: {"type": "Sub-polar or polar barren-lichen-moss", "color": "#408a70"},
    14: {"type": "Wetland", "color": "#6ba38a"},
    15: {"type": "Cropland", "color": "#e6ae66"},
    16: {"type": "Barren land", "color": "#a8abae"},
    17: {"type": "Urban and built-up", "color": "#DD40D6"},
    18: {"type": "Water", "color": "#4c70a3"},
    19: {"type": "Snow and ice", "color": "#eee9ee"},
}
smokey_bear_names = {
    1: "Low",
    2: "Moderate",
    3: "High",
    4: "Very High",
    5: "Extreme",
    6: "No data at this location.",
}
smokey_bear_styles = {
    1: "#2b83ba",
    2: "#abdda4",
    3: "#ffffbf",
    4: "#fdae61",
    5: "#d7191c",
    6: "#ffffff",
}
snow_status = {
    1: "Sea",
    2: False,
    3: "Sea ice",
    4: True,
    0: "No data at this location.",
}

place_type_labels = {
    "huc": "HUC",
    "protected_area": "Protected Area",
    "borough": "Borough",
    "census_area": "Census Area",
    "fire_zone": "Fire Management Unit",
    "corporation": "Corporation",
    "climate_division": "Climate Division",
    "ethnolinguistic_region": "Ethnolinguistic Region",
    "first_nation": "Canadian First Nation",
    "game_management_unit": "Game Management Unit",
}

cached_urls = [
    "/eds/all/",
    "/alfresco/flammability/local/",
    "/alfresco/veg_type/local/",
    "/beetles/point/",
    "/elevation/point/",
    "/taspr/point/",
    "/indicators/base/point/",
    "/ncr/permafrost/point/",
    "/eds/hydrology/point/",
    "/alfresco/flammability/area/",
    "/alfresco/veg_type/area/",
    "/beetles/area/",
    "/elevation/area/",
    "/taspr/area/",
    "/indicators/base/area/",
]

# Used for generating output for vector_data for /places/all
all_jsons = [
    "communities",
    "hucs",
    "protected_areas",
    "corporations",
    "climate_divisions",
    "ethnolinguistic_regions",
    "fire_zones",
    "game_management_units",
    "first_nations",
    "boroughs",
    "census_areas",
]

# Look-up table for expected value for the NCR application.
# TODO: Change these in NCR so we don't need this LUT.
areas_near = {
    "borough": "ak_boros_near",
    "census_area": "ak_censusarea_near",
    "climate_division": "climate_divisions_near",
    "corporation": "corporations_near",
    "ethnolinguistic_region": "ethnolinguistic_regions_near",
    "fire_zone": "fire_management_units_near",
    "game_management_unit": "game_management_units_near",
    "first_nation": "ca_first_nations_near",
    "huc": "hucs_near",
    "protected_area": "protected_areas_near",
}

# table to decode field names for demographic data from GeoServer
# fields that were not truncated do not appear here
# see data dictionary in the repo for more info: https://github.com/ua-snap/epa-justice/blob/main/README.md
demographics_fields = {
    "moe_pct_in": "moe_pct_insured",
    "moe_pct_un": "moe_pct_uninsured",
    "moe_pct_w_": "moe_pct_w_disability",
    "pct_65_plu": "pct_65_plus",
    "pct_africa": "pct_african_american",
    "pct_amer_i": "pct_amer_indian_ak_native",
    "pct_below_": "pct_below_150pov",
    "pct_diabet": "pct_diabetes",
    "pct_hawaii": "pct_hawaiian_pacislander",
    "pct_hispan": "pct_hispanic_latino",
    "pct_insure": "pct_insured",
    "pct_minori": "pct_minority",
    "pct_no_bba": "pct_no_bband",
    "pct_no_hsd": "pct_no_hsdiploma",
    "pct_under_": "pct_under_18",
    "pct_unde_1": "pct_under_5",
    "pct_uninsu": "pct_uninsured",
    "pct_w_disa": "pct_w_disability",
    "total_popu": "total_population",
}

# dict to translate species IDs into common and scientific names
species_crosswalk = {'columbiasp': {'common_name': 'Columbia Spotted Frog',
  'scientific_name': 'Rana luteiventris'},
 'longtoedsa': {'common_name': 'Long-toed Salamander',
  'scientific_name': 'Ambystoma macrodactylum'},
 'nwsalamand': {'common_name': 'Northwestern Salamander',
  'scientific_name': 'Ambystoma gracile'},
 'redleggedf': {'common_name': 'Red-legged Frog',
  'scientific_name': 'Rana aurora'},
 'roughskinn': {'common_name': 'Rough-skinned Newt',
  'scientific_name': 'Taricha granulosa'},
 'westerntoa': {'common_name': 'Western Toad',
  'scientific_name': 'Anaxyrus boreas'},
 'woodfrog': {'common_name': 'Wood Frog',
  'scientific_name': 'Lithobates sylvaticus'},
 'ag_squirel': {'common_name': 'Arctic Ground Squirrel',
  'scientific_name': 'Urocitellus parryii'},
 'ak_hare': {'common_name': 'Alaska Hare', 'scientific_name': 'Lepus othus'},
 'ak_marmot': {'common_name': 'Alaska Marmot',
  'scientific_name': 'Marmota broweri'},
 'aktny_shrw': {'common_name': 'Alaska Tiny Shrew',
  'scientific_name': 'Sorex yukonicus'},
 'alxdr_wolf': {'common_name': 'Alexander Archipelago Wolf',
  'scientific_name': 'Canis lupus ligoni'},
 'amwtr_shrw': {'common_name': 'American Water Shrew',
  'scientific_name': 'Sorex palustris'},
 'arctic_fox': {'common_name': 'Arctic Fox',
  'scientific_name': 'Vulpes lagopus'},
 'bargd_shrw': {'common_name': 'Barren Ground Shrew',
  'scientific_name': 'Sorex ugyunak'},
 'beard_seal': {'common_name': 'Bearded Seal',
  'scientific_name': 'Erignathus barbatus'},
 'bt_woodrat': {'common_name': 'Bushy-tailed Woodrat',
  'scientific_name': 'Neotoma cinerea'},
 'ca_myotis': {'common_name': 'California Myotis',
  'scientific_name': 'Myotis californicus'},
 'ciner_shrw': {'common_name': 'Cinereus Shrew',
  'scientific_name': 'Sorex cinereus'},
 'colard_pik': {'common_name': 'Collared Pika',
  'scientific_name': 'Ochotona collaris'},
 'dusky_shrw': {'common_name': 'Dusky Shrew',
  'scientific_name': 'Sorex monticolus'},
 'harbr_seal': {'common_name': 'Harbor Seal',
  'scientific_name': 'Phoca vitulina'},
 'hry_marmot': {'common_name': 'Hoary Marmot',
  'scientific_name': 'Marmota caligata'},
 'keen_mytis': {'common_name': "Keen's Myotis",
  'scientific_name': 'Myotis keenii'},
 'lgtail_vol': {'common_name': 'Long-tailed Vole',
  'scientific_name': 'Microtus longicaudus'},
 'lilb_mytis': {'common_name': 'Little Brown Bat',
  'scientific_name': 'Myotis lucifugus'},
 'lole_mytis': {'common_name': 'Long-legged Bat',
  'scientific_name': 'Myotis volans'},
 'meadow_vol': {'common_name': 'Meadow Vole',
  'scientific_name': 'Microtus pennsylvanicus'},
 'mjmp_mouse': {'common_name': 'Meadow Jumping Mouse',
  'scientific_name': 'Zapus hudsonius'},
 'n_fur_seal': {'common_name': 'Northern Fur Seal',
  'scientific_name': 'Callorhinus ursinus'},
 'nbog_lemng': {'common_name': 'Northern Bog Lemming',
  'scientific_name': 'Synaptomys borealis'},
 'nbrn_lemng': {'common_name': 'Nearctic Brown Lemming',
  'scientific_name': 'Lemmus trimucronatus'},
 'ncol_lemng': {'common_name': "Nelson's Collared Lemming",
  'scientific_name': 'Dicrostonyx nelsoni'},
 'nfl_squirl': {'common_name': 'Northern Flying Squirrel',
  'scientific_name': 'Glaucomys sabrinus'},
 'nrdbck_vol': {'common_name': 'Northern Red-backed Vole',
  'scientific_name': 'Clethrionomys rutilus'},
 'nw_dermous': {'common_name': 'Northwestern Deer Mouse',
  'scientific_name': 'Peromyscus keeni'},
 'pac_walrus': {'common_name': 'Pacific Walrus',
  'scientific_name': 'Odobenus rosmarus divergens'},
 'pahbr_seal': {'common_name': 'Pacific Harbor Seal',
  'scientific_name': 'Phoca vitulina richardii'},
 'polar_bear': {'common_name': 'Polar Bear',
  'scientific_name': 'Ursus maritimus'},
 'pygmy_shrw': {'common_name': 'Pygmy Shrew', 'scientific_name': 'Sorex hoyi'},
 'red_squirl': {'common_name': 'Red Squirrel',
  'scientific_name': 'Tamiasciurus hudsonicus'},
 'ringd_seal': {'common_name': 'Ringed Seal',
  'scientific_name': 'Pusa hispida'},
 'root_vole': {'common_name': 'Root Vole',
  'scientific_name': 'Microtus oeconomus'},
 'sihair_bat': {'common_name': 'Silver-haired Bat',
  'scientific_name': 'Lasionycteris noctivagans'},
 'sing_vole': {'common_name': 'Singing Vole',
  'scientific_name': 'Microtus miurus'},
 'snosh_hare': {'common_name': 'Snowshoe Hare',
  'scientific_name': 'Lepus americanus'},
 'spotd_seal': {'common_name': 'Spotted Seal',
  'scientific_name': 'Phoca largha'},
 'sredbk_vol': {'common_name': 'Southern Red-backed Vole',
  'scientific_name': 'Clethrionomys gapperi'},
 'st_sealion': {'common_name': 'Steller Sea Lion',
  'scientific_name': 'Eumetopias jubatus'},
 'taiga_vole': {'common_name': 'Taiga Vole',
  'scientific_name': 'Microtus xanthognathus'},
 'tndra_shrw': {'common_name': 'Tundra Shrew',
  'scientific_name': 'Sorex tundrensis'},
 'woodchuck': {'common_name': 'Woodchuck', 'scientific_name': 'Marmota monax'},
 'al_ck_goos': {'common_name': 'Aleutian Cackling Goose',
  'scientific_name': 'Branta hutchinsii leucopareia'},
 'al_flyctch': {'common_name': 'Alder Flycatcher',
  'scientific_name': 'Empidonax alnorum'},
 'aleut_tern': {'common_name': 'Aleutian Tern',
  'scientific_name': 'Onychoprion aleuticus'},
 'am_gld_plo': {'common_name': 'American Golden Plover',
  'scientific_name': 'Pluvialis dominica'},
 'am_kestrel': {'common_name': 'American Kestrel',
  'scientific_name': 'Falco sparverius'},
 'amer_pipit': {'common_name': 'American Pipit',
  'scientific_name': 'Anthus rubescens'},
 'amer_redst': {'common_name': 'American Redstart',
  'scientific_name': 'Setophaga ruticilla'},
 'an_murelet': {'common_name': 'Ancient Murrelet',
  'scientific_name': 'Synthliboramphus antiquus'},
 'arctc_loon': {'common_name': 'Arctic Loon',
  'scientific_name': 'Gavia arctica'},
 'arctc_tern': {'common_name': 'Arctic Tern',
  'scientific_name': 'Sterna paradisaea'},
 'arctic_war': {'common_name': 'Arctic Warbler',
  'scientific_name': 'Phylloscopus borealis'},
 'at_wdpeckr': {'common_name': 'American Three-toed Woodpecker',
  'scientific_name': 'Picoides dorsalis'},
 'bald_eagle': {'common_name': 'Bald Eagle',
  'scientific_name': 'Haliaeetus leucocephalus'},
 'bank_swalo': {'common_name': 'Bank Swallow',
  'scientific_name': 'Riparia riparia'},
 'barn_swalo': {'common_name': 'Barn Swallow',
  'scientific_name': 'Hirundo rustica'},
 'bb_plover': {'common_name': 'Black-bellied Plover',
  'scientific_name': 'Pluvialis squatarola'},
 'bb_sndpipr': {'common_name': 'Broad-billed Sandpiper',
  'scientific_name': 'Calidris falcinellus'},
 'bb_wdpeckr': {'common_name': 'Black-backed Woodpecker',
  'scientific_name': 'Picoides arcticus'},
 'bl_gilemot': {'common_name': 'Black Guillemot',
  'scientific_name': 'Cepphus grylle'},
 'blak_swift': {'common_name': 'Black Swift',
  'scientific_name': 'Cypseloides niger'},
 'blcp_chkde': {'common_name': 'Black-capped Chickadee',
  'scientific_name': 'Poecile atricapillus'},
 'blk_oystca': {'common_name': 'Black Oystercatcher',
  'scientific_name': 'Haematopus bachmani'},
 'blk_scoter': {'common_name': 'Black Scoter',
  'scientific_name': 'Melanitta americana'},
 'blk_trnstn': {'common_name': 'Black Turnstone',
  'scientific_name': 'Arenaria melanocephala'},
 'blklgd_kit': {'common_name': 'Black-legged Kittiwake',
  'scientific_name': 'Rissa tridactyla'},
 'bluethroat': {'common_name': 'Bluethroat',
  'scientific_name': 'Luscinia svecica'},
 'bo_waxwing': {'common_name': 'Bohemian Waxwing',
  'scientific_name': 'Bombycilla garrulus'},
 'boreal_owl': {'common_name': 'Boreal Owl',
  'scientific_name': 'Aegolius funereus'},
 'borl_chkde': {'common_name': 'Boreal Chickadee',
  'scientific_name': 'Poecile hudsonicus'},
 'bp_warbler': {'common_name': 'Blackpoll Warbler',
  'scientific_name': 'Setophaga striata'},
 'brant': {'common_name': 'Brant', 'scientific_name': 'Branta bernicla'},
 'brown_cree': {'common_name': 'Brown Creeper',
  'scientific_name': 'Certhia americana'},
 'brthi_curl': {'common_name': 'Bristle-thighed Curlew',
  'scientific_name': 'Numenius tahitiensis'},
 'bt_godwit': {'common_name': 'Bar-tailed Godwit',
  'scientific_name': 'Limosa lapponica'},
 'c_yelothrt': {'common_name': 'Common Yellowthroat',
  'scientific_name': 'Geothlypis trichas'},
 'cack_goose': {'common_name': 'Cackling Goose',
  'scientific_name': 'Branta hutchinsii'},
 'cas_auklet': {'common_name': "Cassin's Auklet",
  'scientific_name': 'Ptychoramphus aleuticus aleuticus'},
 'cb_chicdee': {'common_name': 'Chestnut-backed Chickadee',
  'scientific_name': 'Poecile rufescens'},
 'ch_sparrow': {'common_name': 'Chipping Sparrow',
  'scientific_name': 'Spizella passerina'},
 'com_eider': {'common_name': 'Common Eider',
  'scientific_name': 'Somateria mollissima'},
 'com_loon': {'common_name': 'Common Loon', 'scientific_name': 'Gavia immer'},
 'com_redpol': {'common_name': 'Common Redpoll',
  'scientific_name': 'Acanthis flammea'},
 'comm_murre': {'common_name': 'Common Murre',
  'scientific_name': 'Uria aalge'},
 'comm_raven': {'common_name': 'Common Raven',
  'scientific_name': 'Corvus corax'},
 'cre_auklet': {'common_name': 'Crested Auklet',
  'scientific_name': 'Aethia cristatella'},
 'dkey_junco': {'common_name': 'Dark-eyed Junco',
  'scientific_name': 'Junco hyemalis'},
 'do_wdpeckr': {'common_name': 'Downy Woodpecker',
  'scientific_name': 'Dryobates pubescens'},
 'dovekie': {'common_name': 'Dovekie', 'scientific_name': 'Alle alle'},
 'dunlin': {'common_name': 'Dunlin', 'scientific_name': 'Calidris alpina'},
 'empr_goose': {'common_name': 'Emperor Goose',
  'scientific_name': 'Chen canagica'},
 'fox_sparow': {'common_name': 'Fox Sparrow',
  'scientific_name': 'Passerella iliaca'},
 'gc_kinglet': {'common_name': 'Golden-crowned Kinglet',
  'scientific_name': 'Regulus satrapa'},
 'gc_rsyfnch': {'common_name': 'Gray-crowned Rosy Finch',
  'scientific_name': 'Leucosticte tephrocotis'},
 'gc_sparrow': {'common_name': 'Golden-crowned Sparrow',
  'scientific_name': 'Zonotrichia atricapilla'},
 'gh_chicade': {'common_name': 'Gray-headed Chickadee',
  'scientific_name': 'Poecile cinctus'},
 'glauc_gull': {'common_name': 'Glaucous Gull',
  'scientific_name': 'Larus hyperboreus'},
 'glwi_gull': {'common_name': 'Glaucous-winged Gull',
  'scientific_name': 'Larus glaucescens'},
 'gold_eagle': {'common_name': 'Golden Eagle',
  'scientific_name': 'Aquila chrysaetos'},
 'gray_jay': {'common_name': 'Gray Jay',
  'scientific_name': 'Perisoreus canadensis'},
 'grgray_owl': {'common_name': 'Great Gray Owl',
  'scientific_name': 'Strix nebulosa'},
 'grwf_goose': {'common_name': 'Greater White-fronted Goose',
  'scientific_name': 'Anser albifrons'},
 'gyrfalcon': {'common_name': 'Gyrfalcon',
  'scientific_name': 'Falco rusticolus'},
 'ha_wdpeckr': {'common_name': 'Hairy Woodpecker',
  'scientific_name': 'Picoides villosus'},
 'herng_gull': {'common_name': 'Herring Gull',
  'scientific_name': 'Larus smithsonianus'},
 'horn_grebe': {'common_name': 'Horned Grebe',
  'scientific_name': 'Podiceps auritus'},
 'hornd_lark': {'common_name': 'Horned Lark',
  'scientific_name': 'Eremophila alpestris'},
 'horned_puf': {'common_name': 'Horned Puffin',
  'scientific_name': 'Fratercula corniculata'},
 'hrmt_thrsh': {'common_name': 'Hermit Thrush',
  'scientific_name': 'Catharus guttatus'},
 'hry_redpol': {'common_name': 'Hoary Redpoll',
  'scientific_name': 'Acanthis hornemanni'},
 'hud_godwit': {'common_name': 'Hudsonian Godwit',
  'scientific_name': 'Limosa haemastica'},
 'killdeer': {'common_name': 'Killdeer',
  'scientific_name': 'Charadrius vociferus'},
 'king_eider': {'common_name': 'King Eider',
  'scientific_name': 'Somateria spectabilis'},
 'kingfisher': {'common_name': 'Belted Kingfisher',
  'scientific_name': 'Megaceryle alcyon'},
 'kit_murlet': {'common_name': "Kittlitz's Murrelet",
  'scientific_name': 'Brachyramphus brevirostris'},
 'la_longspr': {'common_name': 'Lapland Longspur',
  'scientific_name': 'Calcarius lapponicus'},
 'lea_auklet': {'common_name': 'Least Auklet',
  'scientific_name': 'Aethia pusilla'},
 'les_yelolg': {'common_name': 'Lesser Yellowlegs',
  'scientific_name': 'Tringa flavipes'},
 'lesr_scaup': {'common_name': 'Lesser Scaup',
  'scientific_name': 'Aythya affinis'},
 'lgtl_duck': {'common_name': 'Long-tailed Duck',
  'scientific_name': 'Clangula hyemalis'},
 'li_sparrow': {'common_name': "Lincoln's Sparrow",
  'scientific_name': 'Melospiza lincolnii'},
 'lngbl_dowi': {'common_name': 'Long-billed Dowitcher',
  'scientific_name': 'Limnodromus scolopaceus'},
 'lt_jaeger': {'common_name': 'Long-tailed Jaeger',
  'scientific_name': 'Stercorarius longicaudus'},
 'mac_warblr': {'common_name': 'Mangrove Warbler',
  'scientific_name': 'Setophaga petechia'},
 'mbl_godwit': {'common_name': 'Marbled Godwit',
  'scientific_name': 'Limosa fedoa'},
 'mbl_murlet': {'common_name': 'Marbled Murrelet',
  'scientific_name': 'Brachyramphus marmoratus'},
 'mc_bunting': {'common_name': "McKay's Bunting",
  'scientific_name': 'Plectrophenax hyperboreus'},
 'mew_gull': {'common_name': 'Short-billed Gull',
  'scientific_name': 'Larus brachyrhynchus'},
 'no_flicker': {'common_name': 'Northern Flicker',
  'scientific_name': 'Colaptes auratus'},
 'no_harrier': {'common_name': 'Northern Harrier',
  'scientific_name': 'Circus cyaneus'},
 'no_shrike': {'common_name': 'Northern Shrike',
  'scientific_name': 'Lanius excubitor'},
 'no_wheater': {'common_name': 'Northern Wheatear',
  'scientific_name': 'Oenanthe oenanthe'},
 'nor_hawk_o': {'common_name': 'Northern Hawk-Owl',
  'scientific_name': 'Surnia ulula'},
 'oc_warbler': {'common_name': 'Orange-crowned Warbler',
  'scientific_name': 'Leiothlypis celata'},
 'os_flyctch': {'common_name': 'Olive-sided Flycatcher',
  'scientific_name': 'Contopus cooperi'},
 'pac_goldnp': {'common_name': 'Pacific Golden Plover',
  'scientific_name': 'Pluvialis fulva'},
 'pacif_loon': {'common_name': 'Pacific Loon',
  'scientific_name': 'Gavia pacifica'},
 'pacif_wren': {'common_name': 'Pacific Wren',
  'scientific_name': 'Troglodytes pacificus'},
 'par_auklet': {'common_name': 'Parakeet Auklet',
  'scientific_name': 'Aethia psittacula'},
 'pe_cormrnt': {'common_name': 'Pelagic Cormorant',
  'scientific_name': 'Phalacrocorax pelagicus'},
 'pe_sndpipr': {'common_name': 'Pectoral Sandpiper',
  'scientific_name': 'Calidris melanotos'},
 'peal_falcn': {'common_name': "Peale's Falcon",
  'scientific_name': 'Falco peregrinus pealei'},
 'per_falcon': {'common_name': 'Peregrine Falcon',
  'scientific_name': 'Falco peregrinus'},
 'pi_grosbek': {'common_name': 'Pine Grosbeak',
  'scientific_name': 'Pinicola enucleator'},
 'pi_guilmot': {'common_name': 'Pigeon Guillemot',
  'scientific_name': 'Cepphus columba'},
 'pin_siskin': {'common_name': 'Pine Siskin',
  'scientific_name': 'Spinus pinus'},
 'pom_jaeger': {'common_name': 'Pomarine Jaeger',
  'scientific_name': 'Stercorarius pomarinus'},
 'ps_flycach': {'common_name': 'Western Flycatcher',
  'scientific_name': 'Empidonax difficilis'},
 'qchr_gshwk': {'common_name': 'Queen Charlotte Goshawk',
  'scientific_name': 'Accipiter gentilis laingi'},
 'rb_sapsckr': {'common_name': 'Red-breasted Sapsucker',
  'scientific_name': 'Sphyrapicus ruber'},
 'rdtht_loon': {'common_name': 'Red-throated Loon',
  'scientific_name': 'Gavia stellata'},
 'red_crsbil': {'common_name': 'Red Crossbill',
  'scientific_name': 'Loxia curvirostra'},
 'red_knot': {'common_name': 'Red Knot',
  'scientific_name': 'Calidris canutus'},
 'red_phlrop': {'common_name': 'Red Phalarope',
  'scientific_name': 'Phalaropus fulicarius'},
 'rf_cormrnt': {'common_name': 'Red-faced Cormorant',
  'scientific_name': 'Phalacrocorax urile'},
 'rl_kitiwak': {'common_name': 'Red-legged Kittiwake',
  'scientific_name': 'Rissa brevirostris'},
 'rn_grebe': {'common_name': 'Red-necked Grebe',
  'scientific_name': 'Podiceps grisegena'},
 'rn_phalrop': {'common_name': 'Red-necked Phalarope',
  'scientific_name': 'Phalaropus lobatus'},
 'ro_sndpipr': {'common_name': 'Rock Sandpiper',
  'scientific_name': 'Calidris ptilocnemis'},
 'ru_blckbrd': {'common_name': 'Rusty Blackbird',
  'scientific_name': 'Euphagus carolinus'},
 'rubcr_king': {'common_name': 'Ruby-crowned Kinglet',
  'scientific_name': 'Corthylio calendula'},
 'ruf_humbrd': {'common_name': 'Rufous Hummingbird',
  'scientific_name': 'Selasphorus rufus'},
 'ruflg_hawk': {'common_name': 'Rough-legged Hawk',
  'scientific_name': 'Buteo lagopus'},
 'rw_blakbrd': {'common_name': 'Red-winged Blackbird',
  'scientific_name': 'Agelaius phoeniceus'},
 'sanderling': {'common_name': 'Sanderling',
  'scientific_name': 'Calidris alba'},
 'sav_sparow': {'common_name': 'Savannah Sparrow',
  'scientific_name': 'Passerculus sandwichensis'},
 'sb_dowichr': {'common_name': 'Short-billed Dowitcher',
  'scientific_name': 'Limnodromus griseus'},
 'se_sndpipr': {'common_name': 'Semipalmated Sandpiper',
  'scientific_name': 'Calidris pusilla'},
 'shtear_owl': {'common_name': 'Short-eared Owl',
  'scientific_name': 'Asio flammeus'},
 'sm_longspr': {'common_name': "Smith's Longspur",
  'scientific_name': 'Calcarius pictus'},
 'sng_sparow': {'common_name': 'Song Sparrow',
  'scientific_name': 'Melospiza melodia'},
 'sno_buntng': {'common_name': 'Snow Bunting',
  'scientific_name': 'Plectrophenax nivalis'},
 'snowy_owl': {'common_name': 'Snowy Owl',
  'scientific_name': 'Bubo scandiacus'},
 'so_sndpipr': {'common_name': 'Solitary Sandpiper',
  'scientific_name': 'Tringa solitaria'},
 'sp_sndpipr': {'common_name': 'Spotted Sandpiper',
  'scientific_name': 'Actitis macularius'},
 'spec_eider': {'common_name': 'Spectacled Eider',
  'scientific_name': 'Somateria fischeri'},
 'stel_eider': {'common_name': "Steller's Eider",
  'scientific_name': 'Polysticta stelleri'},
 'stelar_jay': {'common_name': "Steller's Jay",
  'scientific_name': 'Cyanocitta stelleri'},
 'surfbird': {'common_name': 'Surfbird',
  'scientific_name': 'Calidris virgata'},
 'swn_thrush': {'common_name': "Swainson's Thrush",
  'scientific_name': 'Catharus ustulatus'},
 'tft_puffin': {'common_name': 'Tufted Puffin',
  'scientific_name': 'Fratercula cirrhata'},
 'thbi_murre': {'common_name': 'Thick-billed Murre',
  'scientific_name': 'Uria lomvia'},
 'to_warbler': {'common_name': "Townsend's Warbler",
  'scientific_name': 'Setophaga townsendi'},
 'tre_sparow': {'common_name': 'American Tree Sparrow',
  'scientific_name': 'Spizelloides arborea'},
 'tree_swalo': {'common_name': 'Tree Swallow',
  'scientific_name': 'Tachycineta bicolor'},
 'trmpt_swan': {'common_name': 'Trumpeter Swan',
  'scientific_name': 'Cygnus buccinator'},
 'upld_sandp': {'common_name': 'Upland Sandpiper',
  'scientific_name': 'Bartramia longicauda'},
 'var_thrush': {'common_name': 'Varied Thrush',
  'scientific_name': 'Ixoreus naevius'},
 'w_scrchowl': {'common_name': 'Western Screech Owl',
  'scientific_name': 'Megascops kennicottii'},
 'wandr_tatt': {'common_name': 'Wandering Tattler',
  'scientific_name': 'Tringa incana'},
 'wc_sparrow': {'common_name': 'White-crowned Sparrow',
  'scientific_name': 'Zonotrichia leucophrys'},
 'we_sndpipr': {'common_name': 'Western Sandpiper',
  'scientific_name': 'Calidris mauri'},
 'whimbrel': {'common_name': 'Whimbrel',
  'scientific_name': 'Numenius phaeopus'},
 'wlsn_wrblr': {'common_name': "Wilson's Warbler",
  'scientific_name': 'Cardellina pusilla'},
 'woodpeewee': {'common_name': 'Western Wood Pewee',
  'scientific_name': 'Contopus sordidulus'},
 'wsk_auklet': {'common_name': 'Whiskered Auklet',
  'scientific_name': 'Aethia pygmaea'},
 'ww_scoter': {'common_name': 'White-winged Scoter',
  'scientific_name': 'Melanitta deglandi'},
 'ye_warbler': {'common_name': 'Yellow Warbler',
  'scientific_name': 'Setophaga petechia'},
 'yelobil_ln': {'common_name': 'Yellow-billed Loon',
  'scientific_name': 'Gavia adamsii'},
 'yelothroat': {'common_name': 'Common Yellowthroat',
  'scientific_name': 'Geothlypis trichas'}}
