name: Run Pytest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gdal-bin \
            libgdal-dev \
            libspatialindex-dev \
            libproj-dev \
            libgeos-dev \
            libblas-dev \
            liblapack-dev \
            gfortran

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install scipy and scientific computing dependencies first
        run: |
          pip install scipy numpy

      - name: Install dependencies
        env:
          GDAL_VERSION: 3.4.1
        run: |
          # Install scientific computing dependencies first
          pip install --upgrade setuptools wheel
          # Install dependencies via pipenv
          pipenv install --dev --system --verbose
          # Ensure pytest is available
          pip install pytest

      - name: Set PYTHONPATH and environment variables
        run: |
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "GDAL_DATA=/usr/share/gdal" >> $GITHUB_ENV
          echo "PROJ_LIB=/usr/share/proj" >> $GITHUB_ENV

      - name: Verify installation
        run: |
          python -c "import sys; print('Python version:', sys.version)"
          python -c "import numpy; print('NumPy version:', numpy.__version__)"
          python -c "import scipy; print('SciPy version:', scipy.__version__)" || echo "SciPy not found"
          python -c "import geopandas; print('GeoPandas version:', geopandas.__version__)" || echo "GeoPandas not found"
          pip list | grep -E "(scipy|numpy|geopandas|rioxarray|xarray)"

      - name: Run tests with pytest
        run: |
          pytest tests/ -v --tb=short
